var annotated_dup =
[
    [ "BluetoothData", "class_bluetooth_data.html", "class_bluetooth_data" ],
    [ "EEPROMUtils", "class_e_e_p_r_o_m_utils.html", "class_e_e_p_r_o_m_utils" ],
    [ "Hackberry", "class_hackberry.html", "class_hackberry" ],
    [ "Hackberry_battery", "class_hackberry__battery.html", "class_hackberry__battery" ],
    [ "Hackberry_bluetooth", "class_hackberry__bluetooth.html", "class_hackberry__bluetooth" ],
    [ "Hackberry_buttons", "class_hackberry__buttons.html", "class_hackberry__buttons" ],
    [ "Hackberry_eeprom", "class_hackberry__eeprom.html", "class_hackberry__eeprom" ],
    [ "Hackberry_hand", "class_hackberry__hand.html", "class_hackberry__hand" ],
    [ "Hackberry_sensor", "class_hackberry__sensor.html", "class_hackberry__sensor" ],
    [ "Hackberry_servos", "class_hackberry__servos.html", "class_hackberry__servos" ],
    [ "HC06", "class_h_c06.html", "class_h_c06" ],
    [ "IBluetoothAT", "class_i_bluetooth_a_t.html", "class_i_bluetooth_a_t" ],
    [ "IRSensor", "class_i_r_sensor.html", "class_i_r_sensor" ],
    [ "ISensor", "class_i_sensor.html", "class_i_sensor" ],
    [ "Mapping_Struct", "struct_mapping___struct.html", "struct_mapping___struct" ],
    [ "Routine_battery", "class_routine__battery.html", "class_routine__battery" ],
    [ "Routine_bluetooth", "class_routine__bluetooth.html", "class_routine__bluetooth" ],
    [ "Routine_buttons", "class_routine__buttons.html", "class_routine__buttons" ],
    [ "Routine_moves", "class_routine__moves.html", "class_routine__moves" ],
    [ "RoutineHandler", "class_routine_handler.html", "class_routine_handler" ],
    [ "servo_t", "structservo__t.html", "structservo__t" ],
    [ "ServoPin_t", "struct_servo_pin__t.html", "struct_servo_pin__t" ],
    [ "servoSequencePoint", "structservo_sequence_point.html", "structservo_sequence_point" ],
    [ "VarSpeedServo", "class_var_speed_servo.html", "class_var_speed_servo" ]
];